### ISSUE TITLE
Workflow don't work under macOS Sierra

### ISSUE THREAD

**Issue by josefglatz** [stve/alfred-vpn#1]
Hi,

I have troubles using any of the available vpn alfred workflows. Everytime I try to connect, a error message appears:
![image](https://user-images.githubusercontent.com/2861556/31211266-02d886dc-a998-11e7-952a-e1409d882a59.png)

If I connect through the vpn icon in the toolbar of macOS all is working as expected.

Do you have a tipp for me?

**Comment by stve** [comment]
Hi @josefglatz thanks for trying this out. I also had a similar experience with existing workflows which is why I built this one. Sorry to hear that you've had issues.

I'm still running El Capitan and have not had issues. But I suppose it is possible that the issue is not the OS, but rather something in the code itself.

> Do you have a tipp for me?

You may want to see if you can use `scutil` to manage your VPN from the command line. The core functionality of this library shells out to `scutil` to list/connect/disconnect so in theory if you can do it there, then we should be able to make this work.

```
# list
scutil --nc list

# connect
scutil  --nc start "My VPN"

# disconnect
scutil --nc stop "My VPN"
```

Provided those work for you, then it may just be a regex issue.

**Comment by josefglatz** [comment]
The mentioned commands BASICALLY works, but after executing the dialog of my first comment here in the issue appears. If I connect through the official vpn icon in the icon bar it works.

Seems like, that when starting VPN via CLI has some security related bugs in macOS?

---

EDIT:
Seems like the approach via `scutil` is broken.

Starting VPN connection via AppleScript works:
```applescript
tell application "System Events"
	tell current location of network preferences
		set VPNservice to service "My VPN"
		if exists VPNservice then connect VPNservice
	end tell
end tell
```
Maybe this is any macOS keychain problem. Seems like that is somewhat buggy in High Sierra

---
EDIT2: Asked a question at stackoverflow https://apple.stackexchange.com/questions/312052/scutil-nc-start-vpn-not-working-macos-10-13-high-sierra

**Comment by stve** [comment]
I know this was reported some time ago, but thanks to @larkov this might be fixed. Please try `0.5.0` and reopen if you continue to have difficulty. I haven't used a VPN in a while so apologies that this hasn't been addressed until now.
